fix: fix horiz scrollbar and other CSS issues ENT-5085
openedx/frontend-app-enterprise-public-catalog pull request #166
Opened 2021-12-03 21:36 UTC by binodpant

[1] fix for scrollbar:
    By using hidden, we will not allow scrolling right/left. It was not fully clear to me but it looks like the sentinel divs on top and bottom (the pseudo elements) were responsible for the scrollbars, since none of the content was actually overflowing. However, this avoid the horiz scroll bars in any width

will remove draft status once the other fixes are included/verified

# For all changes

- [ ] Ensure adequate tests are in place (or reviewed existing tests cover changes)

# Only if submitting a visual change

- [ ] Ensure to attach screenshots
- [ ] Ensure to have UX team confirm screenshots

2021-12-08 13:42 UTC, kiram15 requested changes
Once we add in the fix for the hero this looks good!

2021-12-08 13:42 UTC, kiram15 commented on src/components/catalogs/styles/_enterprise_catalogs.scss
> +  overflow-x: hidden; /* avoid horizontal scrollbar */
Could we add additional padding to both skills grey box and course description so that it has the same as on the left?

2021-12-08 21:44 UTC, binodpant commented on src/components/catalogs/styles/_enterprise_catalogs.scss
> +  overflow-x: hidden; /* avoid horizontal scrollbar */
sure! how is this ? added 0.9em padding to both right and left


<img width="1060" alt="Screen Shot 2021-12-08 at 4 42 54 PM" src="https://user-images.githubusercontent.com/528166/145289194-30ece5a5-26ed-4cec-a65f-af5f963e8b59.png">


before is like this

<img width="1065" alt="Screen Shot 2021-12-08 at 4 44 14 PM" src="https://user-images.githubusercontent.com/528166/145289337-9b5099e3-a714-462e-9f7d-b4e6811ee2c4.png">

2021-12-09 16:37 UTC, kiram15 commented on src/components/catalogs/styles/_enterprise_catalogs.scss
> +  overflow-x: hidden; /* avoid horizontal scrollbar */
I think it would be better if only added to the right side? Now the left looks like too much - apologies for the nit

2021-12-09 16:37 UTC, kiram15 approved these changes
One little change with the padding requested but otherwise LGTM!

2021-12-09 19:39 UTC, binodpant commented on src/components/catalogs/styles/_enterprise_catalogs.scss
> +  overflow-x: hidden; /* avoid horizontal scrollbar */
no not at all, thanks for being detailed, I only apply right padding now

2021-12-09 19:55 UTC, merged