draft: no results error and popular course display
openedx/frontend-app-enterprise-public-catalog pull request #187
Opened 2022-01-20 19:14 UTC by alex-sheehan-edx

![image](https://user-images.githubusercontent.com/67655836/150406519-1035c38a-a342-4da8-99b0-3c1812b75da3.png)

# For all changes

- [ ] Ensure adequate tests are in place (or reviewed existing tests cover changes)

# Only if submitting a visual change

- [ ] Ensure to attach screenshots
- [ ] Ensure to have UX team confirm screenshots

2022-01-24 15:59 UTC, kiram15 requested changes
Just some requests for more tests!

2022-01-24 15:59 UTC, kiram15 commented on src/components/catalogSearchResults/CatalogSearchResults.test.jsx
> +  // test('no search results displays NO_DATA_MESSAGE', () => {
I don't think we should comment this out, just remove it

2022-01-24 15:59 UTC, kiram15 commented on src/data/services/EnterpriseCatalogAPIService.js
> +  static fetchDefaultCoursesInCatalog(options) {
Should we add some tests for this file?

2022-01-24 15:59 UTC, kiram15 commented on src/components/catalogNoResultsDeck/CatalogNoResultsDeck.test.jsx
> +describe('catalog no results deck works as expected', () => {
Can we also add a test for removing filters?

2022-01-24 17:11 UTC, binodpant commented on src/components/catalogNoResultsDeck/CatalogNoResultsDeck.jsx
> +export const NO_DATA_MESSAGE = 'No courses were found that match your search. Try ';
Is this message complete?

2022-01-24 17:12 UTC, binodpant commented on src/components/catalogNoResultsDeck/CatalogNoResultsDeck.jsx
> +    redirect += `/?enterprise_catalog_query_titles=${encodeURIComponent(selectedCatalog)}`;
nit: maybe make the `redirect` a const outside the component like `BASE_APP_URL` and interpolate here instead like `${BASE_APP_URL}/?....` ?

2022-01-24 17:13 UTC, binodpant commented on src/components/catalogNoResultsDeck/CatalogNoResultsDeck.jsx
> +  const selectedCatalog = params.enterprise_catalog_query_titles;
This feels like it belongs in a util function somewhere.. even if it's only used here once.. chances are are already using this pattern elsewhere too, to read the query titles etc. It could even be a hook with useMemo if you like but at least a util function would be great I think, like getSelectedCatalogFromURL() or something like that

2022-01-24 17:16 UTC, binodpant commented on src/components/catalogNoResultsDeck/CatalogNoResultsDeck.jsx
> +    EnterpriseCatalogApiService.fetchDefaultCoursesInCatalogWithFacets(defaultCoursesRefinements).then(response => {
I think if you need to fetch data in a component code, you will want to use useEffect to ensure re-rendering does not re-invoke this, for example.

Ideally put this in a hook like `useNoResultsDefaultData()` or similar, use useEffect inside of that and call it here, would be my suggestion

as it stands, I believe it is going to re invoke the backend call on re-renders...

2022-01-24 17:18 UTC, binodpant commented on src/components/catalogNoResultsDeck/CatalogNoResultsDeck.jsx
> +  columns: PropTypes.arrayOf(PropTypes.object),
if known/feasible, shall we try to further specify the PropTypes.shape({ }) for this columns prop?

2022-01-24 17:25 UTC, binodpant commented on src/components/catalogNoResultsDeck/CatalogNoResultsDeck.test.jsx
> +mockGetCatalogApi.mockResolvedValue(csvData);
nit: perhaps better to do this in one statement?

```
const mockGetCatalogApi = jest.spyOn(
  EnterpriseCatalogApiService, 
  'fetchDefaultCoursesInCatalogWithFacets'
).mockResolvedValue(csvData);
```

2022-01-24 17:33 UTC, binodpant commented on src/components/catalogSearchResults/CatalogSearchResults.test.jsx
> +const mockGetCatalogApi = jest.spyOn(EnterpriseCatalogApiService, 'fetchDefaultCoursesInCatalogWithFacets');
ditto as this: https://github.com/openedx/frontend-app-enterprise-public-catalog/pull/187/files#r790989670

2022-01-24 20:30 UTC, alex-sheehan-edx commented on src/components/catalogSearchResults/CatalogSearchResults.test.jsx
> +  // test('no search results displays NO_DATA_MESSAGE', () => {
good catch, that was entirely cruft that I meant to remove hehe...

2022-01-24 20:55 UTC, alex-sheehan-edx commented on src/components/catalogNoResultsDeck/CatalogNoResultsDeck.jsx
> +  const selectedCatalog = params.enterprise_catalog_query_titles;
👍 I'm fine with making this a util function

2022-01-25 21:06 UTC, binodpant commented on src/utils.js
> +export function formatDate(courseRun) {
love this utils file! I was going to do utils too so whoever merges later can refactor/merge

2022-01-26 14:22 UTC, binodpant commented on src/components/catalogSearchResults/CatalogSearchResults.jsx
> +
Just a thought, instead of conditionals later in the code, wouldn't it be simpler to return an altearnative markup/ cmponent here when SearchResults.nbHits === 0 ?

this way the rest of the code can prety much assume that nbHits > 0

Just wondering, to simplify potentially for less branching logic later in render code

2022-01-26 18:15 UTC, alex-sheehan-edx commented on src/components/catalogSearchResults/CatalogSearchResults.jsx
> +
this was solved by the usage of `useEffect` 🥳

2022-01-26 20:48 UTC, kiram15 commented on src/components/catalogNoResultsDeck/CatalogNoResultsDeck.messages.js
> +    defaultMessage: 'No courses were found that match your search. Try ',
There should be two messages, one for courses and one for programs

2022-01-26 20:49 UTC, alex-sheehan-edx commented on src/components/catalogNoResultsDeck/CatalogNoResultsDeck.messages.js
> +    defaultMessage: 'No courses were found that match your search. Try ',
nice catch

2022-01-26 20:59 UTC, kiram15 commented on src/components/catalogNoResultsDeck/CatalogNoResultsDeck.jsx
> +        itemCount={4}
Should we put these in constants?

2022-01-26 21:01 UTC, kiram15 commented on src/components/catalogSearchResults/CatalogSearchResults.jsx
> +          contentType={contentType === CONTENT_TYPE_COURSE ? 'course' : 'program'}
NIT: I would use the constants here instead of string literals

2022-01-26 21:03 UTC, kiram15 commented on src/utils.js
> +export function makePlural(num, string) {
This method could also be used here! https://github.com/openedx/frontend-app-enterprise-public-catalog/blob/16e7a72cad056183976f4b2a43a4954d29df89aa/src/components/programCard/ProgramCard.jsx#L18

2022-01-26 21:05 UTC, kiram15 commented on src/components/catalogSearchResults/CatalogSearchResults.test.jsx
> -  test('no search results displays NO_DATA_MESSAGE', () => {
I think we need some tests for this: if search results = 0, we see the message on the screen, if there are courses but no programs, programs but no courses, etc

2022-01-27 14:49 UTC, binodpant commented on src/components/catalogSearchResults/CatalogSearchResults.test.jsx
> +  const OLD_ENV = process.env;
this is good for now. I would really love to eliminate the use of process.env from our UI level code, and instead all of them just import from config. We can do a cleanup opportunistically instead of in a larger PR but this part looks like it's needed to handle the envs for now

2022-01-27 15:17 UTC, alex-sheehan-edx commented on src/components/catalogSearchResults/CatalogSearchResults.test.jsx
> +  const OLD_ENV = process.env;
👍  it was best practices and I noticed that this test didn't have the rest of old envs

2022-01-27 22:18 UTC, alex-sheehan-edx commented on src/components/catalogSearchResults/CatalogSearchResults.jsx
> +    if (refinements.q && refinements.q !== '') {
I noticed a small bug where clicking the clear input field would result in a query param of an empty string. This would make this value display as `""` instead of nothing.

2022-01-31 15:04 UTC, kiram15 approved these changes
Looks good! 🚀 👍

2022-01-31 19:53 UTC, merged