Bpant/ent 4124 tabular display of catalog
openedx/frontend-app-enterprise-public-catalog pull request #2
Opened 2021-03-08 19:46 UTC by binodpant

- [ ] fix issue where the env vars for algolia are not being picked up

2021-03-09 14:08 UTC, raq929 approved these changes

2021-03-09 14:08 UTC, raq929 commented on src/components/LoadingMessage/index.jsx
> +      Loading...
This loading module is *terrible*, let's not re-use it. In other places in learner-portal we're using `react-skeleton`, it'll create a much nicer loading experience.

2021-03-09 14:08 UTC, raq929 commented on src/components/NotFoundPage.jsx
> +      This content is not available
Check with UX to be sure this is the text we want.

2021-03-09 14:08 UTC, raq929 commented on src/components/NotFoundPage.jsx
> +    <Helmet title={PAGE_TITLE} />
This should be the `PageWrapper` component.

2021-03-09 14:08 UTC, raq929 commented on src/components/PageWrapper.jsx
> +    <div className="text-center py-5">
I think it's unlikely that we'll want `text-center` on an entire page?

2021-03-09 14:08 UTC, raq929 commented on src/index.jsx
> +      mergeConfig({
Yes, awesome, this is definitely the way to be doing this. 
A part of this ticket should also be making a pr on `edx-internal` to add the algolia variables there.

2021-03-09 14:08 UTC, raq929 commented on src/store.js
> +import { applyMiddleware, createStore } from 'redux';
Let's *not* add redux into this project. We don't need it. We can use the `useReducer` hook if we need a reducer, and we can use React context if we need a store.

2021-03-09 15:26 UTC, binodpant commented on src/store.js
> +import { applyMiddleware, createStore } from 'redux';
yeah agreed I had started with a store and now I don't want it

2021-03-09 16:23 UTC, binodpant commented on src/index.jsx
> +      mergeConfig({
filed: https://openedx.atlassian.net/browse/ENT-4289 for that

2021-03-09 16:29 UTC, binodpant commented on src/index.jsx
> +      mergeConfig({
will take care of it before merging this one, it's very simple and small

2021-03-09 20:25 UTC, binodpant commented on src/store.js
> +import { applyMiddleware, createStore } from 'redux';
I remove the store which is not used anyway, I could not remove `react-redux` itself as a dep due to peer dep but yeah it does not use redux store directly anymore

2021-03-09 20:26 UTC, binodpant commented on src/components/PageWrapper.jsx
> +    <div className="text-center py-5">
yes removed this, don't need on entire page and in fact looks better without it

2021-03-09 20:38 UTC, binodpant commented on src/components/NotFoundPage.jsx
> +      This content is not available
ran by Joe, updated text

2021-03-10 14:48 UTC, binodpant commented on src/index.jsx
> +      mergeConfig({
actually no need to hold up this pr for the ENT-4289 work, that will happen once Talia deploys MFE, and merging this in won't deploy it anywhere yet anyway

2021-03-10 16:29 UTC, raq929 requested changes
I've got a few review comments, and this needs tests before it can be merged! Looking good, though!

2021-03-10 16:29 UTC, raq929 commented on .gitignore
> +module.config.js*
Why the * ?

2021-03-10 16:29 UTC, raq929 commented on package.json
> +    "react-loading-skeleton": "^2.2.0",
This will likely get autofixed if we have the dependency bot, but we shouldn't have the `^` anymore.

2021-03-10 16:29 UTC, raq929 commented on src/components/PageWrapper.jsx
> +  <Container size="lg" className="mt-3">
What happens on a small screen?

2021-03-10 16:29 UTC, raq929 commented on src/components/catalogs/CatalogSearchResults.jsx
> +    return (<Skeleton height={25} />);
I think we probably want more than this? Like a skeleton of a table?
Can you put up a screen shot of what this looks like currently?

2021-03-10 16:29 UTC, raq929 commented on src/components/catalogs/CatalogSearchResults.jsx
> +      <StatusAlert
I think there's a warning about the StatusAlert in the tests in AdminPortal. I think if we're adding it here, we should fix the warnings.

2021-03-10 16:29 UTC, raq929 commented on src/components/catalogs/CatalogSearchResults.jsx
> +  const calculatePage = () => {
If you are defining it this function here inside the component, the `useMemo` below is kind of useless. This will always register as a new function and the code inside the `useMemo` will always run.
I'd suggest either moving the definition outside the component, which I like because that makes it testable, or just not memoizing, because this isn't a high-cost operation, so memoizing doesn't seem like a necessary optimization.

2021-03-10 16:29 UTC, raq929 commented on src/components/catalogs/CatalogSearchResults.jsx
> +          isSelectable
Does this table actually need to be selectable? Are people going to perform bulk actions on it? (I don't remember the spec.)

2021-03-10 16:29 UTC, raq929 commented on src/components/catalogs/EnterpriseCatalogs.jsx
> +import Wrapper from '../PageWrapper';
Let's call it `PageWrapper`; imports get really confusing if we rename them; people used to React will expect this to have the same name as it's file name.

2021-03-10 16:29 UTC, raq929 commented on src/components/catalogs/EnterpriseCatalogs.jsx
> +          <div className="search-header-wrapper">
I expect the SearchHeader doesn't currently accept a `className` prop, but for future reference, I'd prefer to pass this in as a prop rather than adding an extra div.

2021-03-10 16:29 UTC, raq929 commented on src/components/catalogs/EnterpriseCatalogs.jsx
> +          <div className="search-header-wrapper">
Also, I'm not seeing this class used?

2021-03-10 16:29 UTC, raq929 commented on src/index.scss
> +.bg-brand-primary {
Please wrap this in your search header class. `bg-brand-primary` is a css class that might be re-used. We don't want this to accidentally override other styles.
Also, please move this css into the `components/catalogs` folder and import it here. I know we do this in admin portal, but in general, css should live with it's components and the `index.scss` file should *only* contain imports.

2021-03-10 16:30 UTC, binodpant commented on .gitignore
> +module.config.js*
ah yeah I found it convenient to often rename my module.config.js to module.config.js.unused or similar rather than delete and forget what I need.. so this helps with that while keeping current behavior

2021-03-10 16:30 UTC, binodpant commented on package.json
> +    "react-loading-skeleton": "^2.2.0",
yeah I missed this one but will clean it up here instead of waiting for the tool ty

2021-03-10 16:35 UTC, binodpant commented on src/components/PageWrapper.jsx
> +  <Container size="lg" className="mt-3">
it works just fine, and checked the doc, 
```
<Container size="lg" className="bg-danger-300 mb-4">
  The content in this container won't exceed the large width.
</Container>
```

 it appears the lg is mainly about not extending beyond a certain width

2021-03-10 16:37 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> +    return (<Skeleton height={25} />);
hmm when I forced it to show always to see what this shows, and right now I. just see this (should I add a paragon loading spinner in side of this here?)

<img width="1239" alt="Screen Shot 2021-03-10 at 11 36 44 AM" src="https://user-images.githubusercontent.com/528166/110663959-fd50b580-8194-11eb-8c8a-7d6cc23a4940.png">

2021-03-10 16:37 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> +    return (<Skeleton height={25} />);
it's just a animated hardly visible gray bar right now

2021-03-10 16:45 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> +    return (<Skeleton height={25} />);
ah single line skeleton right now and small height so looks hard to find, what about this?
<img width="1239" alt="Screen Shot 2021-03-10 at 11 45 39 AM" src="https://user-images.githubusercontent.com/528166/110665249-29b90180-8196-11eb-8c03-8dc930e2c6b9.png">

2021-03-10 16:46 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> +      <StatusAlert
yeah I just saw onClose is a required field somehow.. .perhaps we need to add it even if not used?

2021-03-10 16:55 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> +      <StatusAlert
hmm also per paragon docs, looks like Alert should be now used instead of StatusAlert anyway, will make that change

2021-03-10 17:11 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> +      <StatusAlert
now looks like this 
<img width="624" alt="Screen Shot 2021-03-10 at 12 11 04 PM" src="https://user-images.githubusercontent.com/528166/110668822-b5805d00-8199-11eb-9ee1-4b84bc6e0b2a.png">

2021-03-10 17:11 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> +  const calculatePage = () => {
yeah good callout this is leftover from my attempts to debug issue, don't need this useMemo here

2021-03-10 17:14 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> +  const calculatePage = () => {
think this is simpler 

```
  const page = refinementsFromQueryParams.page || (searchState ? searchState.page : 0);
```

2021-03-10 17:16 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> +          isSelectable
nope no use case right now for selectable

2021-03-10 17:18 UTC, binodpant commented on src/components/catalogs/EnterpriseCatalogs.jsx
> +          <div className="search-header-wrapper">
ah yes removing this since this class is not even defined, and it has no visual effect

2021-03-10 17:25 UTC, binodpant commented on src/index.scss
> +.bg-brand-primary {
good suggestion, done!

2021-03-10 17:30 UTC, binodpant commented
all feedback applied!

2021-03-10 18:28 UTC, raq929 commented on src/components/catalogs/styles/_index.scss
> +.enterprise-catalogs-header {
🎉

2021-03-10 18:28 UTC, raq929 commented on src/index.jsx
> -    <AppProvider>
Are we not using AppProvider because we don't need authentication?

2021-03-10 18:28 UTC, raq929 commented on src/components/catalogs/CatalogSearchResults.jsx
> +    return (<Skeleton height={25} />);
Yeah, that'll do for the moment. 😄  We can run it by UX later.

2021-03-10 18:28 UTC, raq929 commented on src/components/catalogs/CatalogSearchResults.jsx
> +      <StatusAlert
Throw a top margin on that, and I think we're good.

2021-03-10 20:53 UTC, binodpant commented on src/index.jsx
> -    <AppProvider>
oh wait ok I do  use it, just in the <App> component

2021-03-10 20:56 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> + * @param {object} args.searchResults Results of search (see: `connectStateResults``)
I do not like the 'hidden-ness' of props like this that come from connected/HOC components, so I feel better when I doc it like this ...

2021-03-10 21:18 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> +      <StatusAlert
done! mt-2 for both alerts

2021-03-10 21:30 UTC, raq929 reviewed
TL; DR More tests please!
What you've got is looking good!

2021-03-10 21:30 UTC, raq929 commented on src/components/catalogs/CatalogSearchResults.jsx
> + * @param {object} args.searchResults Results of search (see: `connectStateResults``)
This is what PropTypes is for? I don't see the point of further documenting it like this, but up to you.

2021-03-10 21:30 UTC, raq929 commented on src/components/catalogs/CatalogSearchResults.jsx
> +  paginationComponent: PaginationComponent = SearchPagination,
At edx we generally use `defaultProps` rather than doing it like this, but I don't really have an issue with it.

2021-03-10 21:30 UTC, raq929 commented on src/components/catalogs/CatalogSearchResults.jsx
> +export default connectStateResults(CoreCatalogSearchResults);
Please use `BaseCatalogSearchResults` instead of `Core`, to be conform with standards used in other repos.

2021-03-10 21:30 UTC, raq929 commented on src/components/NotFoundPage.jsx
> +const NotFoundPage = () => (
It's a very simple page right now, but let's add a test for this component.

2021-03-10 21:30 UTC, raq929 commented on src/components/PageWrapper.jsx
> +const Wrapper = ({ children }) => (
This component also needs tests.

2021-03-10 21:30 UTC, raq929 commented on src/components/app/App.jsx
> +        <PageRoute exact path="/" component={EnterpriseCatalogs} />
I'd like to start this repo off right with testing, and test our routes. 
Example here: https://techdoma.in/react-js-testing/how-to-test-routes-react-router-dom-in-react-using-jest-1

2021-03-10 21:30 UTC, raq929 commented on src/components/catalogs/CatalogSearchResults.jsx
> +    return (<Skeleton className="m-1 loading-skeleton" height={25} count={5} />);
We should test that this is displayed when the `isSearchStalled` is true.

2021-03-10 21:30 UTC, raq929 commented on src/components/catalogs/CatalogSearchResults.jsx
> +      Header: TABLE_HEADERS.courseName,
We should test that the correct table headers are displayed in the document.

2021-03-10 21:30 UTC, raq929 commented on src/components/catalogs/EnterpriseCatalogs.jsx
> +export default function EnterpriseCatalogs() {
I don't think this component needs a lot in terms of testing, but we should test it if at all possible.

2021-03-10 21:30 UTC, raq929 commented on src/components/catalogs/data/hooks.jsx
> +const useAlgoliaIndex = () => {
Please test this hook.

2021-03-10 21:33 UTC, raq929 commented on src/components/catalogs/EnterpriseCatalogs.jsx
> +export default function EnterpriseCatalogs() {
I couldn't find a great way to mock Algolia, though, so... this is the only one I'm kind of willing to skip if necessary.

2021-03-10 21:34 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> + * @param {object} args.searchResults Results of search (see: `connectStateResults``)
yeah some of this may come down to taste / prefs too totally, I just ilke being able to read in the function doc what things are for etc, proptypes tells me the type but not the purpose esp. from 'magical' places like connected components

2021-03-10 21:36 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> +export default connectStateResults(CoreCatalogSearchResults);
this is probably just my years of OOP muscle brain haha. `Base` makes me think of inheritance or components down from there.. and there are not. But I also see consistency as a good way to help understand so happy to change this instead of adding yet another prefix term!

2021-03-10 21:37 UTC, binodpant commented on src/components/app/App.jsx
> +        <PageRoute exact path="/" component={EnterpriseCatalogs} />
yeah there are more than one route, so testing routes is a good idea

2021-03-10 21:37 UTC, binodpant commented on src/components/catalogs/EnterpriseCatalogs.jsx
> +export default function EnterpriseCatalogs() {
this one could get a bit tricky but let me see what can be done.. if seems too much work maybe I will let it be, but yeah worth a try

2021-03-10 22:55 UTC, raq929 commented on src/index.jsx
> -    <AppProvider>
If you're using it, it belongs here; it needs to wrap the entire app, not just the component. Things will get *very* confused if it's not at the top level.

2021-03-11 18:20 UTC, binodpant commented on src/components/catalogs/EnterpriseCatalogs.jsx
> +export default function EnterpriseCatalogs() {
managed to setup a test thatt renders the main component (except the AppProvider part since I want to mock the data that goes into it), using this doc as guide: https://testing-library.com/docs/example-react-router/

2021-03-11 18:20 UTC, binodpant commented on src/components/app/App.jsx
> +        <PageRoute exact path="/" component={EnterpriseCatalogs} />
tested!

2021-03-11 18:42 UTC, binodpant commented on src/components/catalogs/CatalogSearchResults.jsx
> +      Header: TABLE_HEADERS.courseName,
tested!

2021-03-11 18:48 UTC, raq929 approved these changes
I love it! :shipit:

2021-03-11 18:51 UTC, merged