DRAFT: refactoring catalog search to support exec ed content
openedx/frontend-app-enterprise-public-catalog pull request #268
Opened 2022-11-28 22:04 UTC by alex-sheehan-edx

WIP inclusion of exec ed in catalog search + rework of structuring order of components rendered

# For all changes

- [ ] Ensure adequate tests are in place (or reviewed existing tests cover changes)

# Only if submitting a visual change

- [ ] Ensure to attach screenshots
- [ ] Ensure to have UX team confirm screenshots

2022-11-29 16:04 UTC, kiram15 commented on src/components/catalogs/CatalogSearch.jsx
> +import React, { useContext, useState, useMemo, useEffect } from 'react';
nit: alphabetize imports

2022-11-29 16:04 UTC, kiram15 commented on src/components/catalogs/CatalogSearch.jsx
> +    // IFF the catalog query is a la carte, specified course type is exec ed (or course type isn't given)
nit: two f's?

2022-11-29 16:04 UTC, kiram15 commented on src/components/catalogs/CatalogSearch.jsx
> +    // IFF the catalog query is a la carte, specified course type is exec ed (or course type isn't given)
Also this comment is confusing

2022-11-29 16:04 UTC, kiram15 commented on src/constants.js
> +export const EXEC_ED_TITLE = 'Executive Education'
nit: semi colon

2022-11-29 16:04 UTC, kiram15 commented on src/components/catalogs/CatalogSearch.jsx
> +  } else if (specifiedContentType === CONTENT_TYPE_PROGRAM) {
This is more just a point of clarification for me, aren't exec ed courses and not programs? also this if is identical to the one above it so you could just combine them if thats what you're trying to do. If not, this needs to be fixed

2022-11-29 18:14 UTC, marlonkeating commented on src/components/catalogs/CatalogSearch.jsx
> +    let contentToDisplay = contentType ? contentType.slice() : [CONTENT_TYPE_COURSE, CONTENT_TYPE_PROGRAM];
nit: While slice() is a perfectly valid way to make a shallow copy, my general preference is to use an operator that does that specific operation, rather than a function built to do a different operation (but will do the operation you want if you omit certain arguments). 
```suggestion
    let contentToDisplay = contentType ? [...contentType] : [CONTENT_TYPE_COURSE, CONTENT_TYPE_PROGRAM];
```

2022-11-29 22:47 UTC, alex-sheehan-edx commented on src/components/catalogs/CatalogSearch.jsx
> +    // IFF the catalog query is a la carte, specified course type is exec ed (or course type isn't given)
IFF stands for "If and only if"

2022-11-29 22:47 UTC, alex-sheehan-edx commented on src/constants.js
> +export const EXEC_ED_TITLE = 'Executive Education'
🤦

2022-11-29 22:48 UTC, alex-sheehan-edx commented on src/components/catalogs/CatalogSearch.jsx
> +    let contentToDisplay = contentType ? contentType.slice() : [CONTENT_TYPE_COURSE, CONTENT_TYPE_PROGRAM];
love this!

2022-12-07 22:39 UTC, alex-sheehan-edx commented on src/components/catalogSearchResults/CatalogSearchResults.jsx
> +    let subTitle;
there's def a better way to do this

2022-12-07 23:16 UTC, marlonkeating reviewed
I Don't see any large issues, but there's a few things I think we should consider as part of a future refactor (perhaps when we remove the flag gating).

To someone new to the code, it's quite hard to follow a lot of the logic between the particulars of the data table component, Algolia queries, and all the bits of filter logic (+ feature gating).  I think some additional compartmentalization and abstraction could greatly help readability and reusability.

2022-12-07 23:16 UTC, marlonkeating commented on src/components/catalogSearchResults/CatalogSearchResults.jsx
> +  }
clarification: What's the significance of 'null' for CustomRowStatus?  (As opposed to 'undefined' which is the other value used in line 458)

2022-12-07 23:48 UTC, alex-sheehan-edx commented on src/components/catalogSearchResults/CatalogSearchResults.jsx
> +  }
oh uhhh, I figure undefined is preferable here

2022-12-08 16:18 UTC, kiram15 requested changes
Connected w/ Alex offine because there are some problems with some of the courses and programs not showing up as they should, which means changes need to be made before this can be merged in.

2022-12-08 16:18 UTC, kiram15 commented on src/components/catalogSearchResults/CatalogSearchResults.jsx
> +        Cell: ({ row }) => (row.values.entitlements[0].price
The column version properly has price but the cards dont?

2022-12-08 16:18 UTC, kiram15 commented on src/components/catalogSearchResults/CatalogSearchResults.jsx
> +    let subTitle;
Honestly I would break it up into another if else, this way makes sense but its kind of confusing even if its less lines

2022-12-09 16:13 UTC, alex-sheehan-edx commented on src/components/catalogSearchResults/CatalogSearchResults.jsx
> +        Cell: ({ row }) => (row.values.entitlements[0].price
I just forgot to update the cards 🙈

2022-12-09 16:22 UTC, alex-sheehan-edx commented on src/components/catalogSearchResults/CatalogSearchResults.jsx
> +  }
actually, I'm taking that back, I believe this needs to be null.

2022-12-09 16:31 UTC, kiram15 approved these changes
LGTM!

2022-12-09 18:04 UTC, merged