[ENT-8322] feat: askXpert component to show user's query results and adding the ability to tweak them
openedx/frontend-app-enterprise-public-catalog pull request #378
Opened 2024-03-12 08:42 UTC by mahamakifdar19

**Jira Ticket**: https://2u-internal.atlassian.net/browse/ENT-8322
**Description**: Added a new react component to display askXpert query results to the user, allowing him to tweak the results by changing filter value from broad to focus.

**UI Screenshots**:
<img width="1440" alt="Screenshot 2024-03-13 at 3 12 11 PM" src="https://github.com/openedx/frontend-app-enterprise-public-catalog/assets/113524403/b40a7f45-f7d8-41c0-a084-a08239877802">
<img width="1440" alt="Screenshot 2024-03-13 at 3 12 23 PM" src="https://github.com/openedx/frontend-app-enterprise-public-catalog/assets/113524403/8c45165c-4dbe-4c63-a1e1-5fc2fed797b0">

https://github.com/openedx/frontend-app-enterprise-public-catalog/assets/113524403/bf7771b0-9a95-4810-9cb8-0f711d969956

# For all changes

- [ ] Ensure adequate tests are in place (or reviewed existing tests cover changes)

# Only if submitting a visual change

- [ ] Ensure to attach screenshots
- [ ] Ensure to have UX team confirm screenshots

2024-03-13 07:12 UTC, jajjibhai008 commented on src/components/askXpertResultCard/AskXpertResultCard.jsx
> +  const execEdCoursesCount = items.filter(item => item.learning_type === 'Executive Education').length;
We have already constants for these learning types. please use them

2024-03-13 07:34 UTC, mahamakifdar19 commented on src/components/askXpertResultCard/AskXpertResultCard.jsx
> +  const execEdCoursesCount = items.filter(item => item.learning_type === 'Executive Education').length;
@jajjibhai008 It can't be achieved with a single filter since we're using multiple arrays and we need to maintain separate counts for different types, using multiple filters here is more appropriate IMO.

2024-03-13 08:31 UTC, jajjibhai008 commented on src/components/askXpertResultCard/AskXpertResultCard.jsx
> +  const execEdCoursesCount = items.filter(item => item.learning_type === 'Executive Education').length;
As we will get a large array of courses that's the reason I was saying to reduce it in a single iteration. 
btw you can consider this too if it looks good to you

```js
const counts = items.reduce((accumulator, item) => {
  switch(item.learning_type) {
    case 'course':
      accumulator.selfPacedCoursesCount++;
      break;
    case 'program':
      accumulator.selfPacedProgramsCount++;
      break;
    case 'Executive Education':
      accumulator.execEdCoursesCount++;
      break;
    default:
      break;
  }
  return accumulator;
}, { selfPacedCoursesCount: 0, selfPacedProgramsCount: 0, execEdCoursesCount: 0 });

const { selfPacedCoursesCount, selfPacedProgramsCount, execEdCoursesCount } = counts;
```

2024-03-13 10:23 UTC, saleem-latif requested changes

2024-03-13 10:23 UTC, saleem-latif commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.jsx
> +const AskXpertResultCard = ({ taskId, queryTitle, data }) => {
nit: I think `XpertResultCard` would be a better name for this.

2024-03-13 10:23 UTC, saleem-latif commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.jsx
> +    setItems(data);
Why do we need this?

2024-03-13 10:23 UTC, saleem-latif commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.jsx
> +  const getXpertResultsWithThreshold = async (threshold) => {
I think using a custom hook here would be better instead of JS function.

2024-03-13 10:23 UTC, saleem-latif commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.jsx
> +      if (status === 200 && responseData) {
I think we should handle all HTTP status codes. 4XX and 5XX will be error and all other statuses can be considered success. 
More Info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

2024-03-13 10:23 UTC, saleem-latif commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.jsx
> +        setItems([]);
We should also check the error and developer message returned by the server here and handle accordingly.

2024-03-13 10:23 UTC, saleem-latif commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.jsx
> +                    onChange={handleChange}
We should use debouncing mechanism here. You can use https://lodash.com/docs#debounce this is one is already in the dependency list.

2024-03-13 10:23 UTC, saleem-latif commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.jsx
> +  const selfPacedCoursesCount = items.filter(item => item.learning_type === CONTENT_TYPE_COURSE).length;
I think it would be better to use `useMemo` here.

2024-03-13 10:23 UTC, saleem-latif commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.jsx
> +  taskId: null,
I think `taskId` should not be optional, I do not think this component can function without `taskId`.

2024-03-13 10:23 UTC, saleem-latif commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.jsx
> +  taskId: null,
I think `queryTitle` and `data` should also not be optional.

2024-03-13 10:23 UTC, saleem-latif commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.jsx
> +  data: PropTypes.arrayOf(
can we renamed `data` to something more readable?

2024-03-13 10:23 UTC, saleem-latif commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.scss
> +  width: 300px;
I think we should avoid hardcoded values so that design is more responsive.

2024-03-13 10:23 UTC, saleem-latif commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.scss
> +  width: 300px;
Maybe you can use some classes from paragon? https://paragon-openedx.netlify.app/components/layout/

2024-03-13 10:35 UTC, mahamakifdar19 commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.jsx
> +  data: PropTypes.arrayOf(
@saleem-latif this is temporary and would be replace by the attribute name returned by API response.

2024-03-13 11:38 UTC, mahamakifdar19 commented on src/components/aiCuration/askXpertResultCard/AskXpertResultCard.scss
> +  width: 300px;
@saleem-latif When styling the input[type='range'] element's slider track using Paragon classes, it's challenging to directly apply custom Paragon classes to override the default styling. This is because CSS rules targeting input[type='range']::-webkit-slider-runnable-track are specific to the browser's default styling.

2024-03-18 10:14 UTC, saleem-latif approved these changes

2024-03-18 11:01 UTC, jajjibhai008 approved these changes

2024-03-18 11:02 UTC, merged