feat: create react component to all users to input querries and show …
openedx/frontend-app-enterprise-public-catalog pull request #379
Opened 2024-03-12 14:21 UTC by jajjibhai008

**Description**
Jira -> [ENT-8321](https://2u-internal.atlassian.net/browse/ENT-8321)

# For all changes

- [ ] Ensure adequate tests are in place (or reviewed existing tests cover changes)

# Only if submitting a visual change

- [ ] Ensure to attach screenshots
- [ ] Ensure to have UX team confirm screenshots

2024-03-13 10:57 UTC, saleem-latif requested changes

2024-03-13 10:57 UTC, saleem-latif commented on src/components/aiCuration/AskXpert.jsx
> +  const onSubmit = async (query) => {
nit: I think this would be a good candidate for a custom hook.

2024-03-13 10:57 UTC, saleem-latif commented on src/components/aiCuration/AskXpert.jsx
> +      if (acceptableStatusCodes.includes(postRequestStatusCode)) {
A better approach would be 
```
if (postRequestStatusCode >= 400) {
    // Error
} else {
    // Success
}
```

2024-03-13 10:57 UTC, saleem-latif commented on src/components/aiCuration/AskXpert.jsx
> +        const { status: getRequestStatus, data: FinalResponse } = resultsResponse;
nit: Use camelCase for constants. i.e.  use `finalResponse`.

2024-03-13 10:57 UTC, saleem-latif commented on src/components/aiCuration/AskXpert.jsx
> +  const onSubmit = async (query) => {
Actually 2 hooks would be better, one for the post request and another for polling.

2024-03-13 10:57 UTC, saleem-latif commented on src/components/aiCuration/AskXpert.jsx
> +    setIsLoading(false);
We should cancel the polling here as well.

2024-03-13 10:57 UTC, saleem-latif commented on src/components/aiCuration/AskXpert.jsx
> +                  <LoadingBar isLoading={isLoading} />
We should be updating the loading bar based on the result of polling. i.e. increase bar as status changes from pending to in-progress to done/error.

2024-03-13 10:57 UTC, saleem-latif commented on src/components/aiCuration/AskXpert.jsx
> +                  <LoadingBar isLoading={isLoading} />
We will look into adding a better way to update the loading bar in the future.

2024-03-13 10:57 UTC, saleem-latif commented on src/components/aiCuration/AskXpert.jsx
> +            onClick={() => setIsClose(!isClose)}
Can we use `useToggle` here? https://paragon-openedx.netlify.app/components/hooks/usetoggle/

2024-03-13 10:57 UTC, saleem-latif commented on src/components/aiCuration/AskXpertQueryField.jsx
> +  const submitQuery = (value) => {
I think we can skip the function definition and directly call `onSubmit` down there.

2024-03-13 10:57 UTC, saleem-latif commented on src/components/aiCuration/AskXpertQueryField.jsx
> +          if (event.key === 'Enter') {
nit: Use `event. key === "Enter" || event. key === "NumpadEnter"`

2024-03-13 10:57 UTC, saleem-latif commented on src/components/aiCuration/data/service.js
> +      const response = await axios.get(`${EnterpriseCatalogAiCurationApiService.enterpriseCatalogAiCurationServiceUrl}?task_id=${taskId}&&?threshold=${threshold}`);
Here is an example to create a hook with polling https://www.dhiwise.com/post/a-guide-to-real-time-applications-with-react-polling 
We can enhance this example by clearing callback when status success/error is received indicating task completion.

2024-03-13 11:17 UTC, jajjibhai008 commented on src/components/aiCuration/AskXpert.jsx
> +            onClick={() => setIsClose(!isClose)}
For now I can't implement this because we are not rendering this component in the parent. When we render this component in parent while integration then we can achieve this easily.

2024-03-13 14:54 UTC, jajjibhai008 commented on src/components/aiCuration/AskXpert.jsx
> +                  <LoadingBar isLoading={isLoading} />
it some extra effort, and also since the blackened API is not final yet so it's a bit difficult to do this by just assuming things. As this is an extra step so we can achieve this after integration.

2024-03-13 14:56 UTC, jajjibhai008 commented on src/components/aiCuration/AskXpert.jsx
> +  const onSubmit = async (query) => {
We can not create hooks there because we have to call those apis inside the onSumbit function and as per react rules we can not call a hook inside a function.

2024-03-18 10:11 UTC, saleem-latif approved these changes

2024-03-18 10:17 UTC, mahamakifdar19 approved these changes

2024-03-18 10:47 UTC, merged